Develope
ASErshov/WorkWithGitApi pull request #8
Opened 2020-09-11 09:24 UTC by ASErshov

2020-09-11 09:54 UTC, dipiash commented
По интерфейсу получилось хорошо, но есть пару нюансов:
- Страдает адаптив у фильтров
   <img width="320" alt="Снимок экрана 2020-09-11 в 14 51 12" src="https://user-images.githubusercontent.com/14073668/92906913-4a4e0c00-f43e-11ea-9a26-22fcb62ab9cd.png">
- Страдает адаптив у пагинации - вместе с горизонтальной прокруткой таблицы, прокручивается и футер с пагинацией и приходится скроллить обратно, чтобы перейти на следующую страницу
   <img width="381" alt="Снимок экрана 2020-09-11 в 14 52 15" src="https://user-images.githubusercontent.com/14073668/92907158-85503f80-f43e-11ea-8d17-d8cec4a7f43a.png">
- Работа с пагинацией - если мы нашли меньше вариантов нежели выбрано в limit (10/15 и пр.) мы все равно видим управление стрелками и если нажимаем на стрелку, то видим Not Found. По идее если мы видим кол-во элементов меньше лимита пагинации не должно быть?
   <img width="320" alt="Снимок экрана 2020-09-11 в 14 45 28" src="https://user-images.githubusercontent.com/14073668/92906100-a5cbca00-f43d-11ea-83bb-92aadb7ef107.png">

   <img width="320" alt="Снимок экрана 2020-09-11 в 14 45 09" src="https://user-images.githubusercontent.com/14073668/92906027-93ea2700-f43d-11ea-8154-5156d3441d1a.png">
- Наверное стоит немного поработать с отступами между элементами в интерфейсе, чтобы они выглядели идентично

2020-09-11 10:33 UTC, dipiash requested changes

2020-09-11 10:33 UTC, dipiash commented on .vs/ProjectSettings.json
> +{
Наверное `.vs/` лучше в репозитории не хранить

2020-09-11 10:33 UTC, dipiash commented on src/components/CustomTableBody/CustomTableBody.spec.tsx
> +import renderer from 'react-test-renderer'
А почему не используешь `render` из `@testing-library/react`?

2020-09-11 10:33 UTC, dipiash commented on src/components/CustomTableBody/CustomTableBody.spec.tsx
> +import { mount } from 'enzyme'
И почему используешь `enzyme` вместо `@testing-library/react`?

2020-09-11 10:33 UTC, dipiash commented on src/components/CustomTableBody/CustomTableBody.tsx
> +            <TableRow key={`rowindex_${indexRow}`}>
Хорошо ли в данном случае использовать индекс массива как ключ?

2020-09-11 10:33 UTC, dipiash commented on src/components/CustomTableBody/CustomTableBody.tsx
> +               <TableCell align='left' key={`cellIndex_${indexItem}`}>
Хорошо ли в данном случае использовать индекс массива как ключ?

2020-09-11 10:33 UTC, dipiash commented on src/components/CustomTableHead/CustomTableHead.tsx
> +            <TableCell align='center'  key={lable.text} width={lable.width?lable.width:60}>
Наверное стоит настроить по проекту линтер/приттир, потому что тут `'center'  key=` два пробела

2020-09-11 10:33 UTC, dipiash commented on src/components/CustomTableHead/CustomTableHead.tsx
> +    }>
Наверное стоит делать атомарный отдельный тип для этой конструкции?

2020-09-11 10:33 UTC, dipiash commented on src/components/FilterSelect/FilterSelect.tsx
> +const FilterSelect: React.FC<FilterSelectProps> = ({handleSelect, lable, items, selected}): React.ReactElement =>{
А зачем писать возвращаемый тип `React.ReactElement`, если мы уже используем `React.FC`?

2020-09-11 10:33 UTC, dipiash commented on src/components/FilterSelect/FilterSelect.tsx
> +        handleSelect(e.target.value as string|number)
Можем ли мы в этом случае `value` сразу назначить тип, чтобы не кастовать его?

2020-09-11 10:33 UTC, dipiash commented on src/components/FilterSelect/FilterSelect.tsx
> +            >
Тут тоже что-то не так с отступами

2020-09-11 10:33 UTC, dipiash commented on src/components/FilterSelect/FilterSelect.tsx
> +                )}
и тут отступы

2020-09-11 10:33 UTC, dipiash commented on src/components/Loader/Loader.tsx
> +    )
Может быть лучше и проще использовать вместо этого подхода какую-то svg иконку и просто анимировать ее поворот?

И можно ли доработать компонент таким образом, чтобы в него можно было оборачивать другие компоненты и показывать лодер над ними (чтобы у пользователя не прыгал интерфейс)?

2020-09-11 10:33 UTC, dipiash commented on src/components/SearchInput/SearchInput.module.css
> +}
`background-color: #1976D2 !important;` используется одинаковая конструкция, в чем разница?

2020-09-11 10:33 UTC, dipiash commented on src/components/SearchInput/SearchInput.tsx
> +    }
Можно ли обойтись без кастования типов?

2020-09-11 10:33 UTC, dipiash commented on src/components/SearchInput/SearchInput.tsx
> +            {buttonText}
А если `text ` хранится в стейте, то зачем его передавать тут? Почему не использовать его сразу в функции отправки?

2020-09-11 10:33 UTC, dipiash commented on src/features/MainPage/MainPage.tsx
> +          lable={'Поиск по слову'}
Наверное лучше: `Поиск по названию репозитория`

2020-09-11 10:33 UTC, dipiash commented on src/features/MainPage/MainPage.tsx
> +      { error&& <Typography variant='h5' className={styles.error} >{error} </Typography>}
Было бы здорово, если бы у пользователя не прыгал интерфейс при загрузке и работе с данными

2020-09-11 10:33 UTC, dipiash commented on src/features/MainPage/MainRepository.ts
> +          console.error(error)
Стоит обработать как-то эту ошибку и отразить в интерфейсе. Сейчас ведь пользователь не поймет, что произошла ошибка?

2020-09-11 10:33 UTC, dipiash commented on src/features/MainPage/MainRepository.ts
> +      .catch(function (error) {
Если используем async/await может стоит использовать try/catch вместо then/catch?

2020-09-11 10:33 UTC, dipiash commented on src/features/MainPage/MainRepository.ts
> +          console.error(error)
Тут тоже не обработана ошибка

2020-09-11 10:33 UTC, dipiash commented on src/features/MainPage/components/RepoTable/RepoTable.spec.tsx
> +    </Provider>
Может быть стоит заполнять более понятными данными тесты (и в других местах по проекту тоже)?

2020-09-11 10:33 UTC, dipiash commented on src/features/MainPage/components/RepoTable/RepoTable.tsx
> +    const handleChangePage = ( event: React.MouseEvent<HTMLButtonElement, MouseEvent> | null,newPage:number) => {
Как-то везде по разному работает форматирование `= ( ev`, то есть пробел между скобкой, то нет?

2020-09-11 10:33 UTC, dipiash commented on src/features/MainPage/ducks/sagas.ts
> +
Можно как-то декомпозировать формирование запроса и сделать код более понятным на случай если параметров станет еще больше?

2020-09-11 10:33 UTC, dipiash commented on src/features/MainPage/ducks/sagas.ts
> +      yield put(actions.fetchReposSuccses((<{items: Array<Repo>}>data).items))
Почему были выбраны генераторы и саги? В чем их преимущество в данном случае?

2020-09-11 10:34 UTC, dipiash requested changes

2020-09-11 10:34 UTC, dipiash commented on src/features/MainPage/MainRepository.ts
> +export default class MainRepository {
Почему в данном случае используется класс?

2020-09-11 10:48 UTC, inerc commented
<img width="1652" alt="Снимок экрана 2020-09-10 в 21 25 58" src="https://user-images.githubusercontent.com/15797209/92915661-731dd380-f435-11ea-9ecb-d84a60ae327e.png">
Вариниги при сборке

2020-09-11 10:52 UTC, inerc commented
<img width="1472" alt="Снимок экрана 2020-09-11 в 13 51 42" src="https://user-images.githubusercontent.com/15797209/92916197-f2130c00-f435-11ea-9502-b81e52aef2d0.png">

2020-09-11 11:09 UTC, inerc commented on src/components/SearchInput/SearchInput.tsx
> +        <FormControl fullWidth variant="outlined" size='small'>
Все это хорошо бы обернуть в форму, и handleSubmit  вешать не на onClick а на submit формы

2020-09-11 11:09 UTC, inerc commented on src/components/Loader/Loader.spec.tsx
> +import { mount } from 'enzyme'
не используется.

2020-09-11 11:09 UTC, inerc commented on src/components/Loader/Loader.spec.tsx
> +import styles from './Loader.module.css'
не используется.

2020-09-11 11:09 UTC, inerc commented on src/features/MainPage/MainPage.tsx
> +    dispatch(actions.fetchRepos({license: value, text: query.text, page:1, perPage:10}))
mapDispatchToProps

2020-09-11 11:30 UTC, AlexChirkin commented on src/components/CustomTableBody/CustomTableBody.tsx
> +const CustomTableBody: React.FC<TableBodyProps> = ({records}):React.ReactElement => {
может быть?

`import React, {FC, ReactElement} from 'react'`

-> `const CustomTableBody: FC<TableBodyProps> = ({records}):ReactElement => {`

2020-09-11 11:30 UTC, AlexChirkin commented on src/components/FilterSelect/FilterSelect.tsx
> +            style ={{width: '100%'}}
Я бы вынес из компонента в const или добавил claasName и в стили

2020-09-11 11:30 UTC, AlexChirkin commented on src/components/Loader/Loader.tsx
> +    )
Если очень нужно именно так, то теги все таки сразу закрывать `<div/>`

2020-09-11 11:30 UTC, AlexChirkin commented on src/components/SearchInput/SearchInput.module.css
> +    background-color: #1976D2 !important;
Тут и дальше можно ли обойтись без `!important`, стили на кнопке не инлайновые и без проблем перезаписываются

2020-09-11 12:53 UTC, ASErshov commented on .vs/ProjectSettings.json
> +{
Действительно)

2020-09-11 12:55 UTC, ASErshov commented on src/components/CustomTableBody/CustomTableBody.spec.tsx
> +import { mount } from 'enzyme'
С тестами не так давно познакомился, пока тестил на enzyme и react-test-renderer ибо в компании так принято где работаю, но думаю нет проблемы изучить и @testing -library/react

2020-09-11 12:56 UTC, ASErshov commented on src/components/CustomTableBody/CustomTableBody.tsx
> +            <TableRow key={`rowindex_${indexRow}`}>
В данном случае оптимально, ибо это тупенькая компонента которая понятия не имеет что за данные придут ей в таблицу, и по задумке она просто отображает двумерный массив как таблицу, не важно есть у данных id или нет.

2020-09-11 12:56 UTC, ASErshov commented on src/components/CustomTableBody/CustomTableBody.tsx
> +               <TableCell align='left' key={`cellIndex_${indexItem}`}>
В данном случае оптимально, ибо это тупенькая компонента которая понятия не имеет что за данные придут ей в таблицу, и по задумке она просто отображает двумерный массив как таблицу, не важно есть у данных id или нет.

2020-09-11 13:01 UTC, ASErshov commented on src/features/MainPage/MainRepository.ts
> +          console.error(error)
Ошибки которые приходят как ошибки с бэка при hhtp запросах нужны не для конечной версии продукта, а для разрабов, чтобы проверять что пошло не так, и почему запрос крашнулся, пользователю по большому счету не надо знать что запросы крашаться у него всегда должна быть какая-то стабильная картинка.
Кроме особых случаев, правда их я тоже не обрабатывал...

2020-09-11 13:03 UTC, ASErshov commented on src/features/MainPage/components/RepoTable/RepoTable.spec.tsx
> +    </Provider>
может и стоит, но как писал выше, у данной компоненты весь функционал сводится к выводу двумерного массива в виде таблицы, и чтобы это протестить не нужны спецеффические данны. И у остальных компонент из папки copmonents тоже нет особо замысловатого функционала

2020-09-11 13:03 UTC, ASErshov commented on src/features/MainPage/components/RepoTable/RepoTable.tsx
> +    const handleChangePage = ( event: React.MouseEvent<HTMLButtonElement, MouseEvent> | null,newPage:number) => {
а это потому что я не настроил eslint))

2020-09-11 13:06 UTC, ASErshov commented on src/features/MainPage/ducks/sagas.ts
> +
Я обдумывал этот момент, но с бэка приходит слишком много излишних данных, и допустим обычных спретоператоров не хватит, а описывать функцию которая будет только по неообходимым ключам (допустим их можно из типа брать) парсить пришедшие данные ради 6 ячеек я не стал. В случае с большим числом данных это было бы необходимо

2020-09-11 13:11 UTC, ASErshov commented on src/features/MainPage/MainRepository.ts
> +export default class MainRepository {
Класс, потому что все запросы объеденены одной логикой одной областью использования, используются в одном файле саги.
Писать несколько функций (в данном случае 2) и импортить их по отдельности менее удобно чем юзать класс.
Инкапсуляция все дела)

2020-09-11 13:14 UTC, ASErshov commented on src/components/SearchInput/SearchInput.tsx
> +        <FormControl fullWidth variant="outlined" size='small'>
О, а тут толи я глупый толи лыжи не едут, сперва я так и сделал, но сабмит на форме редиректит при сабмите, а избежать этого я чет не смог, когда-то очень давно боролся с этим вроде и даже находил что-то, но тут решил просто отказаться от использования формы

2020-09-11 13:16 UTC, ASErshov commented on src/features/MainPage/MainPage.tsx
> +    dispatch(actions.fetchRepos({license: value, text: query.text, page:1, perPage:10}))
Не вижу смысла смешивать код когда все написано на хуках с mapDispatchToProps и mapStateToProps.
Все же как то принято придержиываться одной стилистики если это хуки то хуки, если контейнерные компоненты с с mapDispatchToProps и mapStateToProps то так.
В том числе чтобы не нагружать код.

2020-09-11 13:17 UTC, ASErshov commented on src/components/CustomTableBody/CustomTableBody.tsx
> +const CustomTableBody: React.FC<TableBodyProps> = ({records}):React.ReactElement => {
Может и так, но по-моему не велика разница если я уже заимпортил React почему не обращаться через него?
По моему это дело вкуса или стилистики кода принятой в компании не так ли?

2020-09-11 13:19 UTC, ASErshov commented on src/components/FilterSelect/FilterSelect.tsx
> +            style ={{width: '100%'}}
Блин, писать файл стилей импортить его, подом обращаться через className.
Несколько строк кода вместо одной...

2020-09-11 13:21 UTC, ASErshov commented on src/components/SearchInput/SearchInput.module.css
> +    background-color: #1976D2 !important;
Это тема со стилями material Ui, их надо было просто написать через createStyle их чтобы important не юзать а так просто без них не работает

2020-09-11 13:57 UTC, AlexChirkin commented on src/components/SearchInput/SearchInput.module.css
> +    background-color: #1976D2 !important;
Самый простой способ без добавления новых классов

`body . submit {
  ....
}`

Также можно сделать через `:global` или вместо `body` навесить класс на `SearchInput` и использовать уже его

2020-09-11 14:17 UTC, ASErshov commented on src/components/SearchInput/SearchInput.module.css
> +    background-color: #1976D2 !important;
Так на SearchInput весит класс, а body . submit {} тупо не хватает у material ui классов преоритет выше все равно.
Можно конечно делать что то типо body div div .submit но это некрасиво.
Надо было просто прописать прям в файле через makeStyles класс и его прикручивать а не модульные вешать, вот и все.

2020-09-14 07:00 UTC, dipiash commented on src/features/MainPage/MainRepository.ts
> +          console.error(error)
Ну я вот поймал ошибку Rate limit'a, нажимаю на любую кнопку или выбираю что-то в селекте и у меня ничего не происходит, я как пользователь не понимаю, что происходит и по какой причине.

<img width="600" alt="Снимок экрана 2020-09-14 в 11 53 44" src="https://user-images.githubusercontent.com/14073668/93053488-4f4ecd80-f681-11ea-853f-18a77eec04c6.png">

2020-09-14 07:02 UTC, dipiash commented on src/features/MainPage/ducks/sagas.ts
> +
Этот запрос формируется на стороне приложения, что значит `но с бэка приходит слишком много излишних данных`?

2020-09-14 08:08 UTC, ASErshov commented on src/features/MainPage/ducks/sagas.ts
> +
А  да сори не туда посмотрел (перепутал с моментом в селектора) видимо отвлекся когда отвечал.

Ну можно просто склеивать строку из объекта который в action.payload лежит по ключу значение пробегаясь в цикле.

2020-09-14 08:11 UTC, ASErshov commented on src/features/MainPage/MainRepository.ts
> +          console.error(error)
Ну да, вот про такие особые случаи я и говорил, просто я на него не напоролся вот и не обработал.

2020-09-14 08:16 UTC, ASErshov commented on src/components/SearchInput/SearchInput.module.css
> +    background-color: #1976D2 !important;
https://material-ui.com/ru/customization/components/

Цитата из доки:
"но вы обязаны принимать во внимание порядок внедрения CSS, поскольку CSS внедренный в DOM через Material-UI имеет максимально возможную специфичность,"

2020-09-14 10:38 UTC, dipiash approved these changes

2020-09-21 16:42 UTC, merged